### ISSUE TITLE
Whenever using development database on production

### ISSUE THREAD

**Issue by skyamgar** [javan/whenever#684]
I am using Whenever v0.9.7 with Rails 4.2.4. whenever is using development database in production also.
Can you help with How to solve this issue??

When i say `whenever` i get following which shows production but database used is wrong.

`45 10 * * * /bin/bash -l -c 'cd /data/swati/Projects/metal && bundle exec bin/rails runner -e production '\''Mixins::UploadMaster.new.upload_data(ErpFile.find(4).table_name, ErpFile.find(4).file_name)'\'' >> /data/swati/Projects/metal/log/cron_log.log 2>&1'`

**Comment by benlangfeld** [comment]
Please provide your database.yml and some details of how you know the wrong database is being used.

**Comment by skyamgar** [comment]
Here is my database.yml

```
  default: &default
  adapter: postgresql
  username: username
  password: password
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/metal_development

test:
  <<: *default
  database: db/metal_test

production:
  <<: *default
  database: db/metal_production
```

And my schedule.rb is as follows: 

```
require File.expand_path('../environment', __FILE__)

set :environment, Rails.env.to_sym
set :output, ENV["CRON_LOG_FILE"]

erp_access = ErpAccess.first

erp_access.erp_files.each do |erp_file|
  if erp_file.start_time
    if erp_file.repeat_hours
      every erp_file.repeat_hours.hours, at: erp_file.start_time do
        toRun = 'Mixins::UploadMaster.new.upload_data(ErpFile.find(' + erp_file.id.to_s + ').table_name, ErpFile.find('+ erp_file.id.to_s + ').file_name)'
        runner toRun
      end
    end
  end
end
```
And the time shown above 10:45 is retrieved from development database as in production database i have set the time of 7:40.

Also I tried changing the database as follows:

```
development:
  <<: *default
  database: db/metal_production
```

which then retrieved the correct time 7:40 pm.
